### ISSUE TITLE
Penalty is wrong - especially in teams

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#142]
2633AE74E446E64F442128FD5E89
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/0191a1b9-8250-480c-8357-7d0317bf6903)

**Comment by EdwardPiwowar** [comment]
Currently, the bot does not double due to lack of HCP. But with 13 HCP:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1692a4c7-9dc5-45e2-ae3a-a4f6aa8c84d5)

**Comment by ThePokerDude** [comment]
Fixed in 8137
But I had to manually enter all bids until 3s.
I do net get why east does not bid Michaels but 1d now?
![image](https://github.com/user-attachments/assets/f96b9383-bbc9-44ea-8402-33752a616be0)
and here without manual intervention, Here you can cvlearly see the downsides of not showing the two suiter:
you don't find the spade fit
![image](https://github.com/user-attachments/assets/5deb7e60-6756-4cb6-908c-d8eb972ab507)

**Comment by EdwardPiwowar** [comment]
No Michaels for S+D, but there was a bug.
Next BBA
![image](https://github.com/user-attachments/assets/2704a9c6-b0e2-45eb-9c5b-d59f51f846f0)
