### ISSUE TITLE
Filtering interesting deals

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#191]
I would like to find some deals where the bidding goes

2C-2D
2Ma

It seems I can enter
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/ff8964f9-4fb3-42de-9a89-c3836636e128)

and the make the search for each suit.

I would also like to have hands where responder starts with Pass

Is it possible to enter something like ```*2C-*-2D-*-2*``` ? (Perhaps a regular expression on the bidding could be an option)

**Comment by EdwardPiwowar** [comment]
It may be 
p-p-1H-X
but for now I'm using a very simple comparison,
which only catches identical matches.
I'll find time to expand it a bit.

**Comment by ThorvaldAagaard** [comment]
OK, Trying to find 2C-P-3N - That is not easy

**Comment by EdwardPiwowar** [comment]
Write the exact expression (with variants), I will try.

**Comment by EdwardPiwowar** [comment]
[BiddingAnalyser.exe.zip](https://github.com/EdwardPiwowar/BBA/files/13998824/BiddingAnalyser.exe.zip)
You can use "*" instead of each character. "?" means 1 or 2 characters.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/fb9af1f1-0267-4b45-8ff7-923c6ec1cd82)
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/611f0e67-5179-44f0-b886-238e753330cf)

**Comment by ThorvaldAagaard** [comment]
Is it case sensitive?

I entered just 2C and it gave me a load of deals where there was no 2C bid.

How do I filter for a specific opening?

**Comment by EdwardPiwowar** [comment]
Type 
2C-
"-" must be due to the possibility of using the text for other purposes.
It not is sensitive.
Today I will add new possibility like:
6-p-p-p

**Comment by EdwardPiwowar** [comment]
The sequence must contain at least one "-" character.
