### ISSUE TITLE
new version still penaly doubles when they are making overtricks and not in game

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#342]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/e755a143-c9b2-4bd4-bbdd-3a31a8fdabab)
001F243FAE55507171BFBABF0347

So at table one north with no extras and 2 small trumps makes a penalty double into game.  this is making overtricks.

**Comment by ThePokerDude** [comment]
Fixed in 8627
![image](https://github.com/user-attachments/assets/12e1ed62-423c-4da6-ac7c-9ccd6b311f05)
![image](https://github.com/user-attachments/assets/aa764d07-7109-4511-8000-b9b790c33388)
![image](https://github.com/user-attachments/assets/7187e634-1a14-4c0a-b74e-4a820a5aa981)
![image](https://github.com/user-attachments/assets/03be7d3a-de70-4622-873a-d0e8cf1c14f6)
![image](https://github.com/user-attachments/assets/7aecd46d-1091-4fa9-8b28-67364ee42117)
![image](https://github.com/user-attachments/assets/c5692a40-e779-4ade-8391-5855e0a19f12)
