### ISSUE TITLE
no raise with 6 card support

### ISSUE THREAD

**Issue by Muppet1** [EdwardPiwowar/BBA#404]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/2ceb8b7c-7eca-4f32-9dc0-01edad928040)
1A1EB4BFA8991A01F186393BB208

table one had a sane auction.

table two didn't manage to bid game in either direction.

**Comment by ThorvaldAagaard** [comment]
I prefer the 2S opening at table 2, and North has a clear 4S bid. Then it is interesting if East should enter hoping to find a cheap sacrifice.

A good rule is that if you after a 1 major has a Jacoby 2N bid, then you just bid game when partner opens a weak 2.

**Comment by ThePokerDude** [comment]
Not fixed in 8091
Table 1 -north should bid 4s
With 10 trumps in M you should bid 4M always (exceptions in vul vs not vul possible)
With 11+ trumps in M you should bid 4M always

Table 2 - when opponents agree on hearts, it's sure partner has spades. After 4h p p north has to bis 4s.
I understand that handling multi is not easy. Four humans this would be obvious. 
To do define a rule which excludes options in parner's hand based on opponents' bidding is difficult, I think.

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/f0082a74-12b8-4b21-8475-56fa7fe2314d)

**Comment by EdwardPiwowar** [comment]
In some situations BBA does not follow the above rules. This applies to a strong card with ugly points, but in this case BBA should bid 4S.
I added Andreas' suggestion after opening the multi, because it seems obvious here.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/46ac8d59-1ca8-4c6c-870b-750a55ddd22f)

**Comment by ThePokerDude** [comment]
Fixed in 8629
![image](https://github.com/user-attachments/assets/ae2a7d87-e23c-40ce-8d55-546caba9fe6b)
![image](https://github.com/user-attachments/assets/6588f902-eef0-41c8-b820-73a60cc55766)
