### ISSUE TITLE
Rookie bidding

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#416]
8AD05AB1C91715990FF4366DCDD3
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/bb0a761b-f60a-4fb9-a66c-660b652d68af)

This is one of these situation, where Texas for followed by 4N is the way to slam (grand)

![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/7c4e3e3e-3cfb-4e33-a17c-b53564cdd3fd)
After getting 3 Aces and trump Q, any Q will make 7, and worst case it is on a finesse, but a lot of extra chances.

By the Way 4H is not a calculated bid, but FORCED

**Comment by ThePokerDude** [comment]
8091 bids 6h but the 4nt (quantitative) seems too pessimistic to me. 6card h with a top honour heavy hand is worth a RKCB.
We need to agree on what we bid with these 3 options
a) game, no slam interest
b) game, slam invitation
c) slam strength 

I think with no slam interest at all best is

1nt p 4d p 4h p p - because the responder just passes to 4h and no misunderstanding is possible
If we agree on this then
1nt p 2d p 2h p 4h - shows slam invitation
Opener passes with a weak hand and continues with extra values

With a hand which wants to try slam indepndently of openers strength we bid

1nt p 4d p 4h p 4s/4nt (depending on if we play kickback 4s is either cuebid or 4KCB)

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/78b90c66-6ded-431c-bd44-88829e12e7b1)

**Comment by ThorvaldAagaard** [comment]
Sounds like I have described it for BBA. With 5-card major unbal you just bid new suit at the 3-level - So 4N is quant with 5332

**Comment by ThorvaldAagaard** [comment]
> Thorvald explain "By the Way 4H is not a calculated bid, but FORCED" pls.

After opening 1N and partner bids 4D, opener should not look at his hand, but just bid 4H. That is what I mean by forced.

You bid 4D if you have no slam interest, or if your hand is good enough to continue with RKC

**Comment by EdwardPiwowar** [comment]
You are right, but BBA marks the bid as "calculated" by default in the case of an agreed suit.
Tomorrow I will try to implement this second sentence and see how it works.

**Comment by ThePokerDude** [comment]
Not yet fixed in 8101
Correct bidding s
1n p 4d p
4h p 4nt p
5c (0 or 3) p 5d p
5nt (Qh no king) p 7h

7h is not 100% sure
East can count
6 heart tricks
AK club
AK diamond
AK spade
for a total of 12

In worst case we have a 50% chance because of the diamond finesse +
the chance that partner has a queen in club, diamond or spade
If not he case there is the chance that partner has a doubleton in diamonds for a diamond ruff 
or the chance that partner has 5 spades or clubs and we can ruff the log suit high.
I do not know how to accuratly calulate the chances of 7h but should be above 60%.

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/3515deab-ea5f-4e1f-98df-5258dd89be12)

**Comment by EdwardPiwowar** [comment]
BridgeBum writes:
"Texas - promise game values, but deny slam values. With a hand interested in slam, responder should start with a Jacoby Transfer and make a forcing rebid at his next turn."
https://www.bridgebum.com/texas_transfer.php
but as per your suggestion:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/56e95538-fcbd-4e26-8ab2-f9bb92e46ec0)

**Comment by ThorvaldAagaard** [comment]
Thx, I think I am right https://bridgewinners.com/article/view/texasjacoby-question/ and BridgeBum should update :-)

**Comment by ThePokerDude** [comment]
Fixed in 8140
![image](https://github.com/user-attachments/assets/853582c5-2a9c-4214-9b7c-d95dc6439347)
![image](https://github.com/user-attachments/assets/53b56a66-79f9-4fdc-9eee-4fee9f22c930)
