### ISSUE TITLE
Error in inverted minors

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#434]
4BF29A8E5D6003EE7F88C48ACC05
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1435ea34-8925-404c-a30a-aeb987c256de)

According to the explanation West is showing short Club
The right bid is 2N

The final double only works single dummy, and is obviously wrong.

**Comment by ThePokerDude** [comment]
3c as shortness is wrong because a club shortness has been excluded by the 1c opening which shows 3+clubs.
So there is a contradiction in the explanations of 2c and 3c.
As a consequence east should aim for 6c instead of 6nt.

The final double is wrong because if you do not have a pretty sure setting trick the double often makes declarer play easier.
Here for example declarer is more inclined to play for both spade honours in south hand a nd a drop of 9s.

**Comment by EdwardPiwowar** [comment]
Obvious bug. Next BBA:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5275f328-d697-4f1b-948e-71e50401425c)

**Comment by ThePokerDude** [comment]
In 8101 the bidding is much better - borrect explanation of 3c and no final double on 6nt.
With the given information east should o for 6c instead of 6nt. East does not know tht he cannot ruff with at the short trump side (for example could have 2d and 3h instead of 3d and 2h).
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/b378a0ad-dff0-4d6e-99f5-5b20fd79e334)
