### ISSUE TITLE
A preemptive 3S should have 4+ spades

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#436]
00A67E9213E470902E7782A9CD20
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/64f8c924-4bf5-4283-80e0-250118658a3a)

**Comment by ThePokerDude** [comment]
Instead of 3s N should either pass or bid 2s (depending on the agreement on 2s)
I think west should bid 2c insted of X.
Whith medium strength (11)12-15 and having a 5card suit X is fine with 5440 and 5431
not with 5332

The reason behind it: 
when having two 8-card fits, one 5-3 and the other one 4-4 we prefer the 4-4 fit 
when having two 8-card fits, one 5-2 and the other one 4-3 we prefer the 5-2 fit 

With a 5332 when bidding the 5card suit you'll often play it in a -2 fit.
If you double instead you'll most often play a 4-3 fit

**Comment by EdwardPiwowar** [comment]
1. BBA does not require 4 cards, I think 3S is ok considering that the opponents have 4C= having a flat hand.
2. Previously, BBA always bid for a suite, but following previous suggestions, it may also bid for a double. Sometimes it's a difficult decision.

**Comment by ThorvaldAagaard** [comment]
I prefer to follow the LAW, 3S is only OK because BBA in East could not bid, and against some NS might have been 3 down doubled losing 500 against a partscore.

**Comment by ThePokerDude** [comment]
8101 bids the same way

![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/d6dea7da-3e6a-4e5a-9ee4-bd2a15d5e01b)

**Comment by EdwardPiwowar** [comment]
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/dfc68072-a4b6-41d7-8b9c-7ba749ba6b60)

**Comment by ThePokerDude** [comment]
Looks good to me
![image](https://github.com/user-attachments/assets/30a4bc05-4355-4e77-af40-ed13ddba68c2)
![image](https://github.com/user-attachments/assets/0f41918b-fb11-4c2c-aea1-c5122e2451a9)
