### ISSUE TITLE
Some bids should not be possible

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#522]
095529FCEAA31FB72D4E4E28573F
In latest version South correctly open 1N

But BEN is trained that in this sequence opener can bid again
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/f2bfe8f0-792e-403a-9a02-008aecd9ea8b)

When playing NMF, Twoway NMF, checkback or other, opener has done his duty after bidding 1N, so both 3 and 4 Ma should not be allowed

**Comment by ThePokerDude** [comment]
Fixed in 8635
![image](https://github.com/user-attachments/assets/885ca8a7-733a-4a7c-a8cd-6da231da8456)
![image](https://github.com/user-attachments/assets/dfa41f7b-9a49-410a-823c-bc16659fa536)
![image](https://github.com/user-attachments/assets/8b899965-dd1e-4b75-a514-8da6ba6c112e)
![image](https://github.com/user-attachments/assets/7e8e291c-7bc1-4da4-9baa-b488f5214c4f)
![image](https://github.com/user-attachments/assets/1c78ff13-ca55-4620-b369-bfebd37fe807)
