### ISSUE TITLE
Missing slam with 7 tricks oppsite a 2C opener

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#643]
08A969B868675A7342FF14E9E81C
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1e387a17-c3a1-4cb9-b1ce-d8bb32606636)

3N with 7 tricks looks very wrong
Even 7D is better.
Actually BEN bid 6D

**Comment by Muppet1** [comment]
![image](https://github.com/EdwardPiwowar/BBA/assets/11272970/096514d5-3179-45c4-ab05-83478f35ee3f)

Not very helpful pretty sure 3h is how good are your hearts and 3s is terrible no idea after that without looking it up.

**Comment by ThePokerDude** [comment]
This is difficult because it requires good/detailed agreements.
Instead 3nt we should bid 4d.
As we have shown modest slam interest 3with 3d already and decline 3nt
4d should show strong slam interest with a very solid suit.

2c p 3d p 
3h p 4d 

Now south should ask for keycards and after hearing 2+ Qd bid 7d.
Not sure how to define a very solid suit, though. 
Something like:

AKQxxx(x)
or for a 6card suit: 4 of the 5 highest cards inclueding the ten
or for a 7card suit: 3 of the 4 highest cards inclueding the jack

**Comment by EdwardPiwowar** [comment]
I'm afraid 4N after minor slam try is to play.
I see two options, the second one is already in the next version of BBA.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/5aa90e55-584f-4af1-abf1-abd6bd00e63b)

**Comment by ThorvaldAagaard** [comment]
Better for now
