### ISSUE TITLE
From the horror cabinet

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#644]
0E8E82B5993CCADFD884F9DC53A7
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1b0259f8-a821-4d85-9352-53c17cedb4cf)
7C looks wrong
The penalty double is just bad

0577FF3A88476C5F45D7E435FC6E
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/6c10ac2b-d355-4ae3-9d09-1c0975dea176)

With a known 10-card fit East should show trump Q, then at least 6S can be bid

0CDE169755DC253E3A36B2284CAB
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d94b979f-aac9-4807-acd0-fe74f06b7d62)
Table 2: Rebidding 3D with 4-card support is wrong

0120039B805DCE36776472803608
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/e4f8e1ba-785f-4f12-98f6-7dda1009e184)

6S??

105E761F904388AD460F26A1BCED
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/05119a7f-548d-4def-a057-21c50de9ddc0)

East should show the 18-19 bal

1C1565D7CE28ED2F4BE92043A3E9
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/d15c30b7-4780-4483-97fa-3b21e7bd22c1)

Asking for aces, but then pass only missing an ace so 7 could still be on

1E57D8F29CC1EA5EFC7586228018
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c87d0016-fb8a-42fc-a2b5-97c756755044)

The splinter is perfect for East at table 2, so missing the slam is bad

1D75637DAE2E0E0960BFBCF01502
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/1128a235-bfe6-445a-b055-2ed0baec13e0)

Really not worth a slam try on the east hand, so pass to 3N 

1625F55DC7B09C490B04EF2610AE
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3cbcc06e-1ca8-4a03-86fe-03213a983508)

4N is just to optimistic

This was the first 26 boards of 433 I recorded long time ago for Soloway Jump shift

**Comment by ThePokerDude** [comment]
B4
0E8E82B5993CCADFD884F9DC53A7
South's hand is a typical semi forcing.
If we do not have a semiforcing opening we should open with 1s.
North should respond with 3nt to 3s 

B11
0577FF3A88476C5F45D7E435FC6E

_With a known 10-card fit East should show trump Q, then at least 6S can be bid_
Definitely - this needs to be hard coded.
Not sure how you implemented the trum queen ask.
The most simple one - you check for quuen trump in the hand of the responder to the question.

A more advanced one would be to keep track of known trumps to each of the bidders.
East knows of 10 and west knows of 9
So for the queen trump ask the more advanced code would look like:
if 
       KnownTrumps >=10 then true
else
      if Trump queen there then true
      else false
end if

B14
0CDE169755DC253E3A36B2284CAB

general rule as opener
if you have fit choose a bid which shows fit immediately
only as responder it is allowed to go for a delayed fit showing

B15
0120039B805DCE36776472803608

Table 1: 3s instead of 6s
related to B14 "only as responder it is allowed to go for a delayed fit showing"
1s p 2d p 2h p - now you bid 3s (if 2s could bo dubleton).
As you are forced to game you show 3+ support in spades and extra values.

Table 2: the jump to 4h is wrong as north should not exclude the possibility of 3nt after 1s p 2d p
It is better to bid 2h instead of 4h - a hand with no extras in HCP

B21
105E761F904388AD460F26A1BCED

west's first bid is wrong - if fit not guaranteed (only 4c) and 5+ cards in onother suit -> bid other suit
so insted of 2c west shoud bid 1d or 2d if 2d shows a strong hand

Afterwards
1c p 2c p - here 3nt 18-19 balanced

B22
1C1565D7CE28ED2F4BE92043A3E9

Table 2
1s p 2c 4h
4nt p 5c p

West passes (probably) because west considers the option of 0 key cards
I propose that you implement a HCP plausiblity check.
2c game force means 12+HCP
Together we have 14+12 (or more) = 26+ HCP -> maximum of 14 HCP missing
HCP of missing key cards = 15 (3 aces + Kc)
-> partner cannot have 0 key cards

B23
1E57D8F29CC1EA5EFC7586228018

As 4h is a calcualted bid the calculation after splinter bids seems wrong
To decide if to continue (cue bid or kcb) or to sign off you should
check a weighted point count
the weight factors should be 1 for cards outside splinter suit, 0.8 for ace in splinter suit, 0.3 for king in splinter suit, 0 for Q and J in splinter suit.
In this situation:
>14/15 weighed points  -> continue 
<14 -> sign off
Off course this model could be refined but I think it could be a good starting point for splinter evaluation

B24 
1D75637DAE2E0E0960BFBCF01502
Table 1
When partner shows 0, so we miss 2 we need to pass to 5d
The calculation behind the 6d bid is wrong.
If we have asked for aces, we have to include the information for our decision/calculation. For a slam the "missing aces" count has to be 1 or less.

B26
1625F55DC7B09C490B04EF2610AE
Table 1 

Here I see two different problems.
Let's say asking for aces is ok -
1st - we should implement 4d as kcb instead of 4nt
2nd - if blackwood is only possible with 4nt then
if trumps are clubs or diamonds we need 5nt as sign off

here after 5s we had to bid a hopeless slam with 2 aces missing.
If 5nt would be sign off, we would have good chances making it.

**Comment by EdwardPiwowar** [comment]
B11
0577FF3A88476C5F45D7E435FC6E
There is a condition for 9 trump and Jack, but there is no condition for 10 trump
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/66341507-36f0-4fca-807f-a8de37e37da1)

**Comment by EdwardPiwowar** [comment]
B14
0CDE169755DC253E3A36B2284CAB
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/828d98cb-58c9-4230-a90c-9e825bf5ef55)

**Comment by EdwardPiwowar** [comment]
B15
0120039B805DCE36776472803608
Currently
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2e3e8fc9-1e2b-46f8-84c2-41fa7c1b487b)
But I think we have an agreement for 4H if 55

**Comment by EdwardPiwowar** [comment]
B21
105E761F904388AD460F26A1BCED
Next BBA
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/f8cd43ea-41bf-4f74-8182-ebc7c1a4abee)

**Comment by EdwardPiwowar** [comment]
B22
1C1565D7CE28ED2F4BE92043A3E9
I will leave this hand because the bidding is different now, but I will check how the hcp plausiblity check works.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/d065bc1c-52b3-4da5-9c1a-7f5e7fe2802d)

**Comment by EdwardPiwowar** [comment]
Currently BBA stops on 5D. RKC at a minor is always a risk and difficult to implementation.
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/0fcf0cdd-7c4c-41e2-bd06-982e29e9df67)

**Comment by ThePokerDude** [comment]
B4 - kind of funny that we end n 3nt if we open but reach slam if we pass. Overall ok.
0E8E82B5993CCADFD884F9DC53A7
![image](https://github.com/user-attachments/assets/0587954c-632b-42f7-a22a-4d0ef3e3d294)
![image](https://github.com/user-attachments/assets/364a6931-8eb7-4a59-bde8-3c45324e89cf)

B11 - very well
0577FF3A88476C5F45D7E435FC6E
![image](https://github.com/user-attachments/assets/f3e7eb44-79c7-41dc-9854-023aa19bc271)

B14 - fixed
0CDE169755DC253E3A36B2284CAB
![image](https://github.com/user-attachments/assets/3d813db4-959f-4d83-9722-62a116d2d728)
![image](https://github.com/user-attachments/assets/4804939b-1b41-4f66-8962-6310602e8ccd)

B15 - looks good to me
0120039B805DCE36776472803608
![image](https://github.com/user-attachments/assets/f97171e9-373b-48fc-81ee-36ec567da5f7)

B21 - wrong implementation. Should be 2nt = 12-14, 3nt = 18-19
105E761F904388AD460F26A1BCED
![image](https://github.com/user-attachments/assets/ce387f0f-6cb4-4e04-a083-4d58f0049f2c)
![image](https://github.com/user-attachments/assets/9d0f92f3-91a1-4598-b11e-ad8c419aeee4)
![image](https://github.com/user-attachments/assets/c7a7828f-1526-47e9-af15-6b97957d9c2c)

B22 - I don't like 5h - we could be too high. I don't like the pass to 5s on T1 - we don't know anything about partner's spades so could be 5-0 fit. On both tables we should bid slam as only 1 keycard is missing.
I'd just bid 5c with the west hand after 4h.
1C1565D7CE28ED2F4BE92043A3E9
![image](https://github.com/user-attachments/assets/ddaf2426-3a7c-4226-8f9b-75eb8d72f7b0)

B23 - still wrong reaction to splinter
1E57D8F29CC1EA5EFC7586228018
![image](https://github.com/user-attachments/assets/e131d335-6f63-4e66-a6ba-7079e9c2e373)

B24 - looks fine to me
1D75637DAE2E0E0960BFBCF01502
![image](https://github.com/user-attachments/assets/5136887f-f7de-451c-ad86-48f38aa5a9db)

B26 - Crosswood does not work?
1625F55DC7B09C490B04EF2610AE
![image](https://github.com/user-attachments/assets/cb8503d1-6816-41f4-b064-c508a8c15821)
![image](https://github.com/user-attachments/assets/1aaa9c2d-adea-4aa6-b129-04a2df9dee01)
![image](https://github.com/user-attachments/assets/3d26c203-690c-4d9d-bd69-8ee0ae756cf9)

**Comment by EdwardPiwowar** [comment]
Thorvald place problems one at a time.
B22
1C1565D7CE28ED2F4BE92043A3E9
According to W, 2 key cards are missing: AS+KS+AC+KC-2 (shown by E) = 2

B26
Next BBA
![image](https://github.com/user-attachments/assets/66727708-a9bc-4c7c-ae88-4d51b3535614)

**Comment by ThorvaldAagaard** [comment]
Ok, I will clean this up and close it.
