### ISSUE TITLE
Disaster of the day

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#670]
04A4B69573528A0FC01F13BDBC79
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/45dc9731-35be-4a7f-ac4b-444291c6133f)

Definition of 4S is wrong

4N followed by 7N is just stupid, as the response always will be 5C when you have all aces

Playing with GIB 3C is Cheaper minor (Second negative) and not 5+ clubs.

The simulation with 5+ clubs resulted in this
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/af6f92ef-ed8f-4984-bf29-cc2b940e0385)

**Comment by ThePokerDude** [comment]
Better but not  perfect with 8137.
RKCB should be used with the intention to make a decision based on the additional information we receive.
In this board we did not receive any aadditional information - it was clear partner will answer 5c.
So we could have bid 6s dircetly as well.
We could have continued to ask after the 5c response and in case partner shows both missing kings bid 7.
This would be ok because than we would intent to use the additional information about the remaining kings.
![image](https://github.com/EdwardPiwowar/BBA/assets/33804161/7468775f-135e-4dc1-bca2-b9bd201dbbc4)

**Comment by ThePokerDude** [comment]
8643 - looks good now.
If partner had two kings we could bid 7.
Now we cannot be sure so stopping in 6s is fine.
![image](https://github.com/user-attachments/assets/72a6350c-ecb4-424e-acf2-4d7fbbe68356)
