### ISSUE TITLE
I would like West to overcall 1NT 

### ISSUE THREAD

**Issue by ThorvaldAagaard** [EdwardPiwowar/BBA#8]
0B88CF8CB9F2232675DE025CD769
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/3e4d6f97-f0e4-46bb-b567-d8a1a1c5c1db)
19E8338EB859EE82041E879071DA
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/c3fe190b-3d85-482d-8b6e-96c9efb1e207)
1126B03E13899DE56C961CE9F42B
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/7e0f5052-7489-4b15-9d1d-c2c5ea90f21b)

**Comment by EdwardPiwowar** [comment]
1
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/11d59eb9-3ea6-44ce-9210-cdb10259c290)

2 There is a problem because WB5 dont play stayman in that situation:
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/1639e73a-b529-4a80-afae-859117594ba8)

3
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/867ac18b-b746-4c50-96b5-661b3ada15d2)

**Comment by ThorvaldAagaard** [comment]
0B88CF8CB9F2232675DE025CD769
![image](https://github.com/EdwardPiwowar/BBA/assets/10560652/7231b1ba-a23c-4424-bfe3-f1b599453278)

Can we get an overcaller with 4333 to pass the Double (XX is bad)

**Comment by EdwardPiwowar** [comment]
ok
![image](https://github.com/EdwardPiwowar/BBA/assets/150140020/2db51b3d-775a-446b-9820-e803b9b5f9b5)
